// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Thu May 05 14:32:26 2016

get_square_intensity get_square_intensity_inst
(
	.vga_xy_rsc_z(vga_xy_rsc_z_sig) ,	// input [19:0] vga_xy_rsc_z_sig
	.x_top_left_rsc_z(x_top_left_rsc_z_sig) ,	// input [9:0] x_top_left_rsc_z_sig
	.y_top_left_rsc_z(y_top_left_rsc_z_sig) ,	// input [9:0] y_top_left_rsc_z_sig
	.width_rsc_z(width_rsc_z_sig) ,	// input [9:0] width_rsc_z_sig
	.height_rsc_z(height_rsc_z_sig) ,	// input [9:0] height_rsc_z_sig
	.video_in_rsc_z(video_in_rsc_z_sig) ,	// input [29:0] video_in_rsc_z_sig
	.intensity_out_rsc_z(intensity_out_rsc_z_sig) ,	// output [9:0] intensity_out_rsc_z_sig
	.last_pixel_rsc_z(last_pixel_rsc_z_sig) ,	// output  last_pixel_rsc_z_sig
	.clk(clk_sig) ,	// input  clk_sig
	.en(en_sig) ,	// input  en_sig
	.arst_n(arst_n_sig) 	// input  arst_n_sig
);

