// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   mg3115@EEWS305-012
//  Generated date: Sat May 07 16:27:02 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    red_detect_core
// ------------------------------------------------------------------


module red_detect_core (
  clk, en, arst_n, vga_xy_rsc_mgc_in_wire_d, video_in_rsc_mgc_in_wire_d, video_out_rsc_mgc_out_stdreg_d,
      redOut_rsc_mgc_out_stdreg_d, endRow_rsc_mgc_out_stdreg_d, endScreen_rsc_mgc_out_stdreg_d
);
  input clk;
  input en;
  input arst_n;
  input [19:0] vga_xy_rsc_mgc_in_wire_d;
  input [29:0] video_in_rsc_mgc_in_wire_d;
  output [29:0] video_out_rsc_mgc_out_stdreg_d;
  reg [29:0] video_out_rsc_mgc_out_stdreg_d;
  output redOut_rsc_mgc_out_stdreg_d;
  reg redOut_rsc_mgc_out_stdreg_d;
  output endRow_rsc_mgc_out_stdreg_d;
  reg endRow_rsc_mgc_out_stdreg_d;
  output endScreen_rsc_mgc_out_stdreg_d;
  reg endScreen_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg [19:0] io_read_vga_xy_rsc_d_cse_sva;
    reg [29:0] io_read_video_in_rsc_d_cse_sva;
    reg slc_svs;
    reg land_1_sva_1;
    reg land_1_lpi_dfm;
    reg land_sva_1;
    reg land_lpi_dfm;

    begin : mainExit
      forever begin : main
        // C-Step 0 of Loop 'main'
        begin : waitLoop0Exit
          forever begin : waitLoop0
            @(posedge clk or negedge ( arst_n ));
            if ( ~ arst_n )
              disable mainExit;
            if ( en )
              disable waitLoop0Exit;
          end
        end
        // C-Step 1 of Loop 'main'
        land_sva_1 = 1'b0;
        land_1_sva_1 = 1'b0;
        io_read_vga_xy_rsc_d_cse_sva = vga_xy_rsc_mgc_in_wire_d;
        io_read_video_in_rsc_d_cse_sva = video_in_rsc_mgc_in_wire_d;
        slc_svs = readslicef_11_1_10((({1'b1 , (~ (io_read_video_in_rsc_d_cse_sva[29:20]))})
            + 11'b110010001));
        if ( slc_svs ) begin
          land_1_sva_1 = readslicef_9_1_8((conv_u2u_8_9(io_read_video_in_rsc_d_cse_sva[9:2])
              + 9'b110110101));
        end
        land_1_lpi_dfm = land_1_sva_1 & slc_svs;
        if ( land_1_lpi_dfm ) begin
          land_sva_1 = readslicef_9_1_8((conv_u2u_8_9(io_read_video_in_rsc_d_cse_sva[19:12])
              + 9'b110110101));
        end
        land_lpi_dfm = land_sva_1 & land_1_lpi_dfm;
        redOut_rsc_mgc_out_stdreg_d <= land_lpi_dfm;
        endRow_rsc_mgc_out_stdreg_d <= ~ (readslicef_11_1_10((({1'b1 , (~ (io_read_vga_xy_rsc_d_cse_sva[9:0]))})
            + 11'b1011)));
        endScreen_rsc_mgc_out_stdreg_d <= (io_read_vga_xy_rsc_d_cse_sva[18]) & (io_read_vga_xy_rsc_d_cse_sva[17])
            & (io_read_vga_xy_rsc_d_cse_sva[16]) & (io_read_vga_xy_rsc_d_cse_sva[15])
            & (~((io_read_vga_xy_rsc_d_cse_sva[19]) | (io_read_vga_xy_rsc_d_cse_sva[14])
            | (io_read_vga_xy_rsc_d_cse_sva[13]) | (io_read_vga_xy_rsc_d_cse_sva[12])
            | (io_read_vga_xy_rsc_d_cse_sva[11]) | (io_read_vga_xy_rsc_d_cse_sva[10])))
            & (io_read_vga_xy_rsc_d_cse_sva[9]) & (io_read_vga_xy_rsc_d_cse_sva[7])
            & (~((io_read_vga_xy_rsc_d_cse_sva[8]) | (io_read_vga_xy_rsc_d_cse_sva[6])
            | (io_read_vga_xy_rsc_d_cse_sva[5]) | (io_read_vga_xy_rsc_d_cse_sva[4])
            | (io_read_vga_xy_rsc_d_cse_sva[3]) | (io_read_vga_xy_rsc_d_cse_sva[2])
            | (io_read_vga_xy_rsc_d_cse_sva[1]) | (io_read_vga_xy_rsc_d_cse_sva[0])));
        video_out_rsc_mgc_out_stdreg_d <= {((io_read_video_in_rsc_d_cse_sva[29:20])
            & (signext_10_1(~ land_lpi_dfm))) , ((io_read_video_in_rsc_d_cse_sva[19:10])
            | ({{9{land_lpi_dfm}}, land_lpi_dfm})) , ((io_read_video_in_rsc_d_cse_sva[9:0])
            & (signext_10_1(~ land_lpi_dfm)))};
      end
    end
    land_lpi_dfm = 1'b0;
    land_sva_1 = 1'b0;
    land_1_lpi_dfm = 1'b0;
    land_1_sva_1 = 1'b0;
    slc_svs = 1'b0;
    io_read_video_in_rsc_d_cse_sva = 30'b0;
    io_read_vga_xy_rsc_d_cse_sva = 20'b0;
    endScreen_rsc_mgc_out_stdreg_d <= 1'b0;
    endRow_rsc_mgc_out_stdreg_d <= 1'b0;
    redOut_rsc_mgc_out_stdreg_d <= 1'b0;
    video_out_rsc_mgc_out_stdreg_d <= 30'b0;
  end


  function [0:0] readslicef_11_1_10;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 10;
    readslicef_11_1_10 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_9_1_8;
    input [8:0] vector;
    reg [8:0] tmp;
  begin
    tmp = vector >> 8;
    readslicef_9_1_8 = tmp[0:0];
  end
  endfunction


  function [9:0] signext_10_1;
    input [0:0] vector;
  begin
    signext_10_1= {{9{vector[0]}}, vector};
  end
  endfunction


  function  [8:0] conv_u2u_8_9 ;
    input [7:0]  vector ;
  begin
    conv_u2u_8_9 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    red_detect
//  Generated from file(s):
//    2) $PROJECT_HOME/red_detect.cpp
// ------------------------------------------------------------------


module red_detect (
  vga_xy_rsc_z, video_in_rsc_z, video_out_rsc_z, redOut_rsc_z, endRow_rsc_z, endScreen_rsc_z,
      clk, en, arst_n
);
  input [19:0] vga_xy_rsc_z;
  input [29:0] video_in_rsc_z;
  output [29:0] video_out_rsc_z;
  output redOut_rsc_z;
  output endRow_rsc_z;
  output endScreen_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [19:0] vga_xy_rsc_mgc_in_wire_d;
  wire [29:0] video_in_rsc_mgc_in_wire_d;
  wire [29:0] video_out_rsc_mgc_out_stdreg_d;
  wire redOut_rsc_mgc_out_stdreg_d;
  wire endRow_rsc_mgc_out_stdreg_d;
  wire endScreen_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(20)) vga_xy_rsc_mgc_in_wire (
      .d(vga_xy_rsc_mgc_in_wire_d),
      .z(vga_xy_rsc_z)
    );
  mgc_in_wire #(.rscid(2),
  .width(30)) video_in_rsc_mgc_in_wire (
      .d(video_in_rsc_mgc_in_wire_d),
      .z(video_in_rsc_z)
    );
  mgc_out_stdreg #(.rscid(3),
  .width(30)) video_out_rsc_mgc_out_stdreg (
      .d(video_out_rsc_mgc_out_stdreg_d),
      .z(video_out_rsc_z)
    );
  mgc_out_stdreg #(.rscid(4),
  .width(1)) redOut_rsc_mgc_out_stdreg (
      .d(redOut_rsc_mgc_out_stdreg_d),
      .z(redOut_rsc_z)
    );
  mgc_out_stdreg #(.rscid(5),
  .width(1)) endRow_rsc_mgc_out_stdreg (
      .d(endRow_rsc_mgc_out_stdreg_d),
      .z(endRow_rsc_z)
    );
  mgc_out_stdreg #(.rscid(6),
  .width(1)) endScreen_rsc_mgc_out_stdreg (
      .d(endScreen_rsc_mgc_out_stdreg_d),
      .z(endScreen_rsc_z)
    );
  red_detect_core red_detect_core_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .vga_xy_rsc_mgc_in_wire_d(vga_xy_rsc_mgc_in_wire_d),
      .video_in_rsc_mgc_in_wire_d(video_in_rsc_mgc_in_wire_d),
      .video_out_rsc_mgc_out_stdreg_d(video_out_rsc_mgc_out_stdreg_d),
      .redOut_rsc_mgc_out_stdreg_d(redOut_rsc_mgc_out_stdreg_d),
      .endRow_rsc_mgc_out_stdreg_d(endRow_rsc_mgc_out_stdreg_d),
      .endScreen_rsc_mgc_out_stdreg_d(endScreen_rsc_mgc_out_stdreg_d)
    );
endmodule



