// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   mg3115@EEWS104A-013
//  Generated date: Tue Mar 08 15:19:31 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    sobel_core
// ------------------------------------------------------------------


module sobel_core (
  clk, en, arst_n, vin_rsc_mgc_in_wire_d, vout_rsc_mgc_out_stdreg_d
);
  input clk;
  input en;
  input arst_n;
  input [89:0] vin_rsc_mgc_in_wire_d;
  output [29:0] vout_rsc_mgc_out_stdreg_d;
  reg [29:0] vout_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg [18:0] FRAME_p_1_lpi_1;
    reg [89:0] regs_regs_1_sva;
    reg [89:0] regs_regs_0_sva;
    reg exit_FRAME_1_sva;
    reg [18:0] FRAME_p_1_lpi_1_dfm;
    reg exit_FRAME_for_lpi_1_dfm;
    reg [89:0] regs_regs_0_sva_1;
    reg [11:0] acc_psp_2_sva;
    reg [3:0] ACC1_acc_107_psp_2_sva;
    reg [2:0] ACC1_acc_116_psp_1_sva;
    reg [2:0] acc_imod_14_sva;
    reg [1:0] acc_imod_16_sva;
    reg [11:0] ACC1_acc_125_psp_1_sva;
    reg [3:0] ACC1_acc_110_psp_2_sva;
    reg [2:0] ACC1_acc_118_psp_1_sva;
    reg [2:0] acc_imod_18_sva;
    reg [1:0] acc_imod_20_sva;
    reg [11:0] acc_10_psp_2_sva;
    reg [3:0] ACC1_acc_113_psp_2_sva;
    reg [2:0] ACC1_acc_120_psp_1_sva;
    reg [2:0] acc_imod_22_sva;
    reg [1:0] acc_imod_24_sva;
    reg [11:0] acc_psp_1_sva;
    reg [3:0] ACC1_acc_107_psp_1_sva;
    reg [2:0] ACC1_acc_116_psp_sva;
    reg [2:0] acc_imod_2_sva;
    reg [1:0] acc_imod_3_sva;
    reg [11:0] ACC1_acc_125_psp_sva;
    reg [3:0] ACC1_acc_110_psp_1_sva;
    reg [2:0] ACC1_acc_118_psp_sva;
    reg [2:0] acc_imod_6_sva;
    reg [11:0] acc_10_psp_1_sva;
    reg [3:0] ACC1_acc_113_psp_1_sva;
    reg [2:0] ACC1_acc_120_psp_sva;
    reg [2:0] acc_imod_10_sva;
    reg [1:0] acc_imod_11_sva;
    reg [1:0] acc_imod_7_lpi_1_dfm;
    reg [89:0] regs_regs_0_sva_dfm;
    reg [89:0] regs_regs_1_sva_dfm;
    reg [11:0] ACC1_acc_125_psp_lpi_1_dfm;
    reg [1:0] i_6_lpi_1_dfm;
    reg [1:0] acc_imod_20_lpi_1_dfm;
    reg [11:0] ACC1_acc_125_psp_1_lpi_1_dfm;
    reg FRAME_for_slc_YMATRIX_rom_11_psp_sva;
    reg [15:0] in_0_sva_1;
    reg [15:0] in_2_sva_1;
    reg [1:0] i_6_sva_1;
    reg exit_FRAME_for_sva_1;
    reg [14:0] intensity_2_sg1_sva;
    reg [5:0] acc_imod_12_sva;
    reg [11:0] FRAME_acc_2_psp_sva;
    reg [18:0] FRAME_p_1_sva_1;
    reg exit_FRAME_lpi_1_dfm_1;
    reg exit_FRAME_for_lpi_1_dfm_2;
    reg exit_FRAME_for_lpi_1_dfm_3;
    reg [12:0] FRAME_for_acc_24_itm_1;
    reg [11:0] FRAME_for_slc_in_0_sva_itm_1;
    reg [11:0] FRAME_for_acc_26_itm_1;
    reg [11:0] FRAME_for_slc_in_2_sva_itm_1;
    reg [12:0] ACC1_acc_341_itm;
    reg [12:0] ACC1_acc_341_itm_1;
    reg exit_FRAME_for_sva_1_st_1;
    reg main_stage_0_2;
    reg [11:0] in_0_sva_2;
    reg [11:0] in_2_sva_2;
    reg [1:0] acc_imod_6_lpi_1_dfm_sg1;
    reg [29:0] regs_regs_2_lpi_1_dfm_sg2;
    reg [29:0] regs_regs_2_lpi_1_dfm_1;
    reg [1:0] ACC1_acc_118_psp_lpi_1_dfm_sg1;
    reg [2:0] ACC1_acc_110_psp_1_lpi_1_dfm_sg1;
    reg [1:0] acc_imod_18_lpi_1_dfm_sg1;
    reg [1:0] ACC1_acc_118_psp_1_lpi_1_dfm_sg1;
    reg [2:0] ACC1_acc_110_psp_2_lpi_1_dfm_sg1;
    reg [2:0] ACC1_acc_197_cse;
    reg [2:0] ACC1_acc_224_cse;
    reg [2:0] ACC1_acc_250_cse;
    reg [2:0] ACC1_acc_277_cse;
    reg FRAME_for_nor_cse;
    reg FRAME_for_slc_XMATRIX_rom_10_psp_sva_1;

    reg[15:0] FRAME_for_mux_11_nl;
    reg[15:0] FRAME_for_mux_12_nl;
    reg[9:0] regs_operator_10_mux_nl;
    reg[9:0] regs_operator_11_mux_nl;
    reg[9:0] regs_operator_9_mux_nl;
    reg[9:0] regs_operator_16_mux_nl;
    reg[9:0] regs_operator_17_mux_nl;
    reg[9:0] regs_operator_15_mux_nl;
    begin : core_rlpExit
      forever begin : core_rlp
        // C-Step 0 of Loop 'core_rlp'
        FRAME_p_1_lpi_1 = 19'b0;
        regs_regs_1_sva = 90'b0;
        regs_regs_0_sva = 90'b0;
        exit_FRAME_1_sva = 1'b1;
        main_stage_0_2 = 1'b0;
        begin : mainExit
          forever begin : main
            // C-Step 0 of Loop 'main'
            begin : waitLoop0Exit
              forever begin : waitLoop0
                @(posedge clk or negedge ( arst_n ));
                if ( ~ arst_n )
                  disable core_rlpExit;
                if ( en )
                  disable waitLoop0Exit;
              end
            end
            // C-Step 1 of Loop 'main'
            if ( main_stage_0_2 ) begin
              FRAME_for_mux_11_nl = MUX_v_16_2_2({in_0_sva_1 , ({{4{FRAME_for_slc_in_0_sva_itm_1[11]}},
                  FRAME_for_slc_in_0_sva_itm_1})}, exit_FRAME_for_lpi_1_dfm_3);
              in_0_sva_1 = conv_s2u_13_16(FRAME_for_acc_24_itm_1) + (FRAME_for_mux_11_nl);
              FRAME_for_mux_12_nl = MUX_v_16_2_2({in_2_sva_1 , ({{4{FRAME_for_slc_in_2_sva_itm_1[11]}},
                  FRAME_for_slc_in_2_sva_itm_1})}, exit_FRAME_for_lpi_1_dfm_3);
              in_2_sva_1 = conv_s2u_12_16(FRAME_for_acc_26_itm_1) + (FRAME_for_mux_12_nl);
              if ( exit_FRAME_for_sva_1_st_1 ) begin
                intensity_2_sg1_sva = readslicef_16_15_1(((in_2_sva_1 + conv_s2s_13_16(ACC1_acc_341_itm_1))
                    + in_0_sva_1));
                acc_imod_12_sva = (conv_u2u_5_6(conv_u2u_4_5(conv_u2u_3_4(intensity_2_sg1_sva[8:6])
                    + conv_u2u_3_4(~ (intensity_2_sg1_sva[11:9]))) + conv_u2u_4_5(conv_u2u_3_4({(~
                    (intensity_2_sg1_sva[14])) , 1'b1 , (~ (intensity_2_sg1_sva[14]))})
                    + conv_u2u_2_4(intensity_2_sg1_sva[13:12]))) + conv_u2u_4_6(conv_u2u_3_4(intensity_2_sg1_sva[2:0])
                    + conv_u2u_3_4(~ (intensity_2_sg1_sva[5:3])))) + 6'b101011;
                FRAME_acc_2_psp_sva = (conv_u2s_11_13(conv_u2s_22_12(conv_u2u_2_11(intensity_2_sg1_sva[13:12])
                    * 11'b111000111)) + conv_s2s_10_12(conv_u2s_9_11(conv_u2s_18_10(conv_u2u_3_9(intensity_2_sg1_sva[11:9])
                    * 9'b111001)) + conv_s2s_8_10(conv_u2s_6_8(intensity_2_sg1_sva[8:3])
                    + conv_s2s_5_8((conv_u2u_4_5(conv_u2u_3_4({(~ (acc_imod_12_sva[5]))
                    , 1'b1 , (~ (readslicef_5_1_4((({1'b1 , (acc_imod_12_sva[2:0])
                    , 1'b1}) + conv_u2s_4_5({(~ (acc_imod_12_sva[5:3])) , (~ (acc_imod_12_sva[5]))})))))})
                    + conv_u2u_2_4(acc_imod_12_sva[4:3])) + conv_u2u_3_5(~ (intensity_2_sg1_sva[8:6])))
                    + ({4'b1001 , (acc_imod_12_sva[5])}))))) + conv_u2u_11_12(signext_11_9({(intensity_2_sg1_sva[14])
                    , 3'b0 , (signext_3_1(intensity_2_sg1_sva[14])) , 1'b0 , (intensity_2_sg1_sva[14])}));
                vout_rsc_mgc_out_stdreg_d <= {((FRAME_acc_2_psp_sva[9:0]) | ({8'b0,
                    FRAME_acc_2_psp_sva[11:10]})) , (FRAME_acc_2_psp_sva[9:6]) ,
                    ((FRAME_acc_2_psp_sva[5:0]) | ({4'b0, FRAME_acc_2_psp_sva[11:10]}))
                    , (FRAME_acc_2_psp_sva[9:0])};
              end
            end
            FRAME_p_1_sva_1 = 19'b0;
            in_2_sva_2 = 12'b0;
            in_0_sva_2 = 12'b0;
            acc_imod_20_sva = 2'b0;
            acc_imod_18_sva = 3'b0;
            ACC1_acc_118_psp_1_sva = 3'b0;
            ACC1_acc_110_psp_2_sva = 4'b0;
            ACC1_acc_125_psp_1_sva = 12'b0;
            FRAME_p_1_lpi_1_dfm = FRAME_p_1_lpi_1 & (signext_19_1(~ exit_FRAME_1_sva));
            exit_FRAME_for_lpi_1_dfm = exit_FRAME_for_lpi_1_dfm_2 | exit_FRAME_1_sva;
            if ( exit_FRAME_for_lpi_1_dfm ) begin
              regs_regs_0_sva_1 = vin_rsc_mgc_in_wire_d;
              acc_psp_2_sva = conv_s2s_11_12(conv_s2s_10_11(~ (regs_regs_0_sva_1[9:0]))
                  + conv_s2s_10_11(~ (regs_regs_0_sva_1[19:10]))) + conv_s2s_11_12(conv_s2s_10_11(~
                  (regs_regs_0_sva_1[29:20])) + 11'b11);
              ACC1_acc_107_psp_2_sva = (readslicef_5_4_1((conv_s2s_4_5({(readslicef_4_3_1((conv_s2s_2_4({(~
                  (acc_psp_2_sva[11])) , 1'b1}) + conv_u2s_2_4({(~ (acc_psp_2_sva[1]))
                  , (acc_psp_2_sva[8])})))) , 1'b1}) + conv_s2s_4_5({2'b10 , (acc_psp_2_sva[0])
                  , (acc_psp_2_sva[10])})))) + conv_u2s_3_4(readslicef_4_3_1((conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(acc_psp_2_sva[2])
                  , 1'b1}) + conv_u2u_2_3({(~ (acc_psp_2_sva[3])) , (~ (acc_psp_2_sva[7]))}))))
                  , 1'b1}) + conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(acc_psp_2_sva[4])
                  , 1'b1}) + conv_u2u_2_3({(~ (acc_psp_2_sva[5])) , (acc_psp_2_sva[6])}))))
                  , (~ (acc_psp_2_sva[9]))}))));
              ACC1_acc_116_psp_1_sva = conv_u2s_2_3(readslicef_3_2_1((conv_u2u_2_3({(ACC1_acc_107_psp_2_sva[0])
                  , 1'b1}) + conv_u2u_2_3({(~ (ACC1_acc_107_psp_2_sva[1])) , (ACC1_acc_107_psp_2_sva[2])}))))
                  + conv_s2s_1_3(~ (ACC1_acc_107_psp_2_sva[3]));
              acc_imod_14_sva = readslicef_4_3_1((conv_s2s_3_4({(~ (ACC1_acc_116_psp_1_sva[2:1]))
                  , 1'b1}) + conv_u2s_2_4({(ACC1_acc_116_psp_1_sva[0]) , 1'b1})));
              acc_imod_16_sva = readslicef_3_2_1((({1'b1 , (acc_imod_14_sva[0]) ,
                  1'b1}) + conv_u2s_2_3({(~ (acc_imod_14_sva[1])) , (~ (acc_imod_14_sva[2]))})));
              ACC1_acc_125_psp_1_sva = conv_s2u_11_12(conv_s2s_10_11(~ (regs_regs_0_sva_1[39:30]))
                  + conv_s2s_10_11(~ (regs_regs_0_sva_1[49:40]))) + conv_s2u_11_12(conv_s2s_10_11(~
                  (regs_regs_0_sva_1[59:50])) + 11'b11);
              ACC1_acc_110_psp_2_sva = readslicef_5_4_1((conv_s2s_4_5({(readslicef_4_3_1((({2'b10
                  , (~ (ACC1_acc_125_psp_1_sva[0])) , 1'b1}) + conv_u2s_3_4({(readslicef_3_2_1((conv_u2u_2_3({(ACC1_acc_125_psp_1_sva[1])
                  , 1'b1}) + conv_u2u_2_3({(~ (ACC1_acc_125_psp_1_sva[2])) , (~ (ACC1_acc_125_psp_1_sva[6]))}))))
                  , (~ (ACC1_acc_125_psp_1_sva[8]))})))) , 1'b1}) + ({(readslicef_5_4_1((conv_u2s_3_5({(readslicef_3_2_1((conv_u2u_2_3({(ACC1_acc_125_psp_1_sva[3])
                  , 1'b1}) + conv_u2u_2_3({(~ (ACC1_acc_125_psp_1_sva[4])) , (ACC1_acc_125_psp_1_sva[5])}))))
                  , 1'b1}) + conv_s2s_3_5({(~ (ACC1_acc_125_psp_1_sva[11:10])) ,
                  (ACC1_acc_125_psp_1_sva[7])})))) , (ACC1_acc_125_psp_1_sva[9])})));
              ACC1_acc_118_psp_1_sva = conv_u2s_2_3(readslicef_3_2_1((conv_u2u_2_3({(ACC1_acc_110_psp_2_sva[0])
                  , 1'b1}) + conv_u2u_2_3({(~ (ACC1_acc_110_psp_2_sva[1])) , (ACC1_acc_110_psp_2_sva[2])}))))
                  + conv_s2s_1_3(~ (ACC1_acc_110_psp_2_sva[3]));
              acc_imod_18_sva = readslicef_4_3_1((conv_s2s_3_4({(~ (ACC1_acc_118_psp_1_sva[2:1]))
                  , 1'b1}) + conv_u2s_2_4({(ACC1_acc_118_psp_1_sva[0]) , 1'b1})));
              acc_imod_20_sva = readslicef_3_2_1((({1'b1 , (acc_imod_18_sva[0]) ,
                  1'b1}) + conv_u2s_2_3({(~ (acc_imod_18_sva[1])) , (~ (acc_imod_18_sva[2]))})));
              acc_10_psp_2_sva = conv_s2s_11_12(conv_s2s_10_11(~ (regs_regs_0_sva_1[69:60]))
                  + conv_s2s_10_11(~ (regs_regs_0_sva_1[79:70]))) + conv_s2s_11_12(conv_s2s_10_11(~
                  (regs_regs_0_sva_1[89:80])) + 11'b11);
              ACC1_acc_113_psp_2_sva = (readslicef_5_4_1((conv_s2s_4_5({(readslicef_4_3_1((conv_s2s_2_4({(~
                  (acc_10_psp_2_sva[11])) , 1'b1}) + conv_u2s_2_4({(~ (acc_10_psp_2_sva[1]))
                  , (acc_10_psp_2_sva[8])})))) , 1'b1}) + conv_s2s_4_5({2'b10 , (acc_10_psp_2_sva[0])
                  , (acc_10_psp_2_sva[10])})))) + conv_u2s_3_4(readslicef_4_3_1((conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(acc_10_psp_2_sva[2])
                  , 1'b1}) + conv_u2u_2_3({(~ (acc_10_psp_2_sva[3])) , (~ (acc_10_psp_2_sva[7]))}))))
                  , 1'b1}) + conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(acc_10_psp_2_sva[4])
                  , 1'b1}) + conv_u2u_2_3({(~ (acc_10_psp_2_sva[5])) , (acc_10_psp_2_sva[6])}))))
                  , (~ (acc_10_psp_2_sva[9]))}))));
              ACC1_acc_120_psp_1_sva = conv_u2s_2_3(readslicef_3_2_1((conv_u2u_2_3({(ACC1_acc_113_psp_2_sva[0])
                  , 1'b1}) + conv_u2u_2_3({(~ (ACC1_acc_113_psp_2_sva[1])) , (ACC1_acc_113_psp_2_sva[2])}))))
                  + conv_s2s_1_3(~ (ACC1_acc_113_psp_2_sva[3]));
              acc_imod_22_sva = readslicef_4_3_1((conv_s2s_3_4({(~ (ACC1_acc_120_psp_1_sva[2:1]))
                  , 1'b1}) + conv_u2s_2_4({(ACC1_acc_120_psp_1_sva[0]) , 1'b1})));
              acc_imod_24_sva = readslicef_3_2_1((({1'b1 , (acc_imod_22_sva[0]) ,
                  1'b1}) + conv_u2s_2_3({(~ (acc_imod_22_sva[1])) , (~ (acc_imod_22_sva[2]))})));
              acc_psp_1_sva = conv_s2s_11_12(conv_s2s_10_11(regs_regs_1_sva[19:10])
                  + conv_s2s_10_11(regs_regs_1_sva[9:0])) + conv_s2s_10_12(regs_regs_1_sva[29:20]);
              ACC1_acc_107_psp_1_sva = (readslicef_5_4_1((conv_s2s_4_5({(readslicef_4_3_1((conv_s2s_2_4({(~
                  (acc_psp_1_sva[11])) , 1'b1}) + conv_u2s_2_4({(~ (acc_psp_1_sva[1]))
                  , (acc_psp_1_sva[8])})))) , 1'b1}) + conv_s2s_4_5({2'b10 , (acc_psp_1_sva[0])
                  , (acc_psp_1_sva[10])})))) + conv_u2s_3_4(readslicef_4_3_1((conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(acc_psp_1_sva[2])
                  , 1'b1}) + conv_u2u_2_3({(~ (acc_psp_1_sva[3])) , (~ (acc_psp_1_sva[7]))}))))
                  , 1'b1}) + conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(acc_psp_1_sva[4])
                  , 1'b1}) + conv_u2u_2_3({(~ (acc_psp_1_sva[5])) , (acc_psp_1_sva[6])}))))
                  , (~ (acc_psp_1_sva[9]))}))));
              ACC1_acc_116_psp_sva = conv_u2s_2_3(readslicef_3_2_1((conv_u2u_2_3({(ACC1_acc_107_psp_1_sva[0])
                  , 1'b1}) + conv_u2u_2_3({(~ (ACC1_acc_107_psp_1_sva[1])) , (ACC1_acc_107_psp_1_sva[2])}))))
                  + conv_s2s_1_3(~ (ACC1_acc_107_psp_1_sva[3]));
              acc_imod_2_sva = readslicef_4_3_1((conv_s2s_3_4({(~ (ACC1_acc_116_psp_sva[2:1]))
                  , 1'b1}) + conv_u2s_2_4({(ACC1_acc_116_psp_sva[0]) , 1'b1})));
              acc_imod_3_sva = readslicef_3_2_1((({1'b1 , (acc_imod_2_sva[0]) , 1'b1})
                  + conv_u2s_2_3({(~ (acc_imod_2_sva[1])) , (~ (acc_imod_2_sva[2]))})));
              ACC1_acc_125_psp_sva = conv_s2u_11_12(conv_s2s_10_11(regs_regs_1_sva[49:40])
                  + conv_s2s_10_11(regs_regs_1_sva[39:30])) + conv_s2u_10_12(regs_regs_1_sva[59:50]);
              ACC1_acc_110_psp_1_sva = readslicef_5_4_1((conv_s2s_4_5({(readslicef_4_3_1((({2'b10
                  , (~ (ACC1_acc_125_psp_sva[0])) , 1'b1}) + conv_u2s_3_4({(readslicef_3_2_1((conv_u2u_2_3({(ACC1_acc_125_psp_sva[1])
                  , 1'b1}) + conv_u2u_2_3({(~ (ACC1_acc_125_psp_sva[2])) , (~ (ACC1_acc_125_psp_sva[6]))}))))
                  , (~ (ACC1_acc_125_psp_sva[8]))})))) , 1'b1}) + ({(readslicef_5_4_1((conv_u2s_3_5({(readslicef_3_2_1((conv_u2u_2_3({(ACC1_acc_125_psp_sva[3])
                  , 1'b1}) + conv_u2u_2_3({(~ (ACC1_acc_125_psp_sva[4])) , (ACC1_acc_125_psp_sva[5])}))))
                  , 1'b1}) + conv_s2s_3_5({(~ (ACC1_acc_125_psp_sva[11:10])) , (ACC1_acc_125_psp_sva[7])}))))
                  , (ACC1_acc_125_psp_sva[9])})));
              ACC1_acc_118_psp_sva = conv_u2s_2_3(readslicef_3_2_1((conv_u2u_2_3({(ACC1_acc_110_psp_1_sva[0])
                  , 1'b1}) + conv_u2u_2_3({(~ (ACC1_acc_110_psp_1_sva[1])) , (ACC1_acc_110_psp_1_sva[2])}))))
                  + conv_s2s_1_3(~ (ACC1_acc_110_psp_1_sva[3]));
              acc_imod_6_sva = readslicef_4_3_1((conv_s2s_3_4({(~ (ACC1_acc_118_psp_sva[2:1]))
                  , 1'b1}) + conv_u2s_2_4({(ACC1_acc_118_psp_sva[0]) , 1'b1})));
              acc_10_psp_1_sva = conv_s2s_11_12(conv_s2s_10_11(regs_regs_1_sva[79:70])
                  + conv_s2s_10_11(regs_regs_1_sva[69:60])) + conv_s2s_10_12(regs_regs_1_sva[89:80]);
              ACC1_acc_113_psp_1_sva = (readslicef_5_4_1((conv_s2s_4_5({(readslicef_4_3_1((conv_s2s_2_4({(~
                  (acc_10_psp_1_sva[11])) , 1'b1}) + conv_u2s_2_4({(~ (acc_10_psp_1_sva[1]))
                  , (acc_10_psp_1_sva[8])})))) , 1'b1}) + conv_s2s_4_5({2'b10 , (acc_10_psp_1_sva[0])
                  , (acc_10_psp_1_sva[10])})))) + conv_u2s_3_4(readslicef_4_3_1((conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(acc_10_psp_1_sva[2])
                  , 1'b1}) + conv_u2u_2_3({(~ (acc_10_psp_1_sva[3])) , (~ (acc_10_psp_1_sva[7]))}))))
                  , 1'b1}) + conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(acc_10_psp_1_sva[4])
                  , 1'b1}) + conv_u2u_2_3({(~ (acc_10_psp_1_sva[5])) , (acc_10_psp_1_sva[6])}))))
                  , (~ (acc_10_psp_1_sva[9]))}))));
              ACC1_acc_120_psp_sva = conv_u2s_2_3(readslicef_3_2_1((conv_u2u_2_3({(ACC1_acc_113_psp_1_sva[0])
                  , 1'b1}) + conv_u2u_2_3({(~ (ACC1_acc_113_psp_1_sva[1])) , (ACC1_acc_113_psp_1_sva[2])}))))
                  + conv_s2s_1_3(~ (ACC1_acc_113_psp_1_sva[3]));
              acc_imod_10_sva = readslicef_4_3_1((conv_s2s_3_4({(~ (ACC1_acc_120_psp_sva[2:1]))
                  , 1'b1}) + conv_u2s_2_4({(ACC1_acc_120_psp_sva[0]) , 1'b1})));
              acc_imod_11_sva = readslicef_3_2_1((({1'b1 , (acc_imod_10_sva[0]) ,
                  1'b1}) + conv_u2s_2_3({(~ (acc_imod_10_sva[1])) , (~ (acc_imod_10_sva[2]))})));
              ACC1_acc_197_cse = conv_u2u_2_3(signext_2_1(acc_psp_1_sva[11])) + conv_u2u_2_3(signext_2_1(acc_psp_1_sva[11]));
              ACC1_acc_224_cse = conv_u2u_2_3(signext_2_1(acc_psp_2_sva[11])) + conv_u2u_2_3(signext_2_1(acc_psp_2_sva[11]));
              in_0_sva_2 = conv_s2s_11_12(conv_u2s_10_11({(acc_psp_1_sva[11]) , 8'b0
                  , (acc_psp_1_sva[11])}) + (conv_s2s_10_11(conv_s2s_8_10(conv_s2s_6_8(conv_s2s_4_6(conv_s2s_3_4((readslicef_4_3_1((conv_s2s_3_4({1'b1
                  , (acc_psp_1_sva[3]) , 1'b1}) + conv_s2s_2_4({(ACC1_acc_107_psp_1_sva[3])
                  , (acc_psp_1_sva[4])})))) + conv_s2s_2_3(ACC1_acc_116_psp_sva[2:1]))
                  + (readslicef_5_4_1((conv_u2s_3_5({(acc_psp_1_sva[3]) , (acc_psp_1_sva[1])
                  , 1'b1}) + conv_s2s_3_5({(ACC1_acc_107_psp_1_sva[3]) , (acc_psp_1_sva[2])
                  , (ACC1_acc_107_psp_1_sva[1])}))))) + conv_u2s_5_6(conv_u2u_4_5({(acc_psp_1_sva[7])
                  , (acc_psp_1_sva[4]) , (signext_2_1(acc_psp_1_sva[11]))}) + conv_u2u_3_5(ACC1_acc_197_cse)))
                  + conv_u2s_7_8({(acc_psp_1_sva[8]) , 1'b0 , (acc_psp_1_sva[8])
                  , 1'b0 , (acc_psp_1_sva[8]) , 1'b0 , (acc_psp_1_sva[8])})) + conv_u2s_8_10(conv_u2u_7_8(signext_7_3({(acc_psp_1_sva[11])
                  , (signext_2_1(acc_psp_1_sva[11]))})) + conv_u2u_6_8(conv_u2u_5_6({(acc_psp_1_sva[6])
                  , 1'b0 , (acc_psp_1_sva[6]) , 1'b0 , (acc_psp_1_sva[6])}) + conv_u2u_4_6(conv_u2u_3_4(ACC1_acc_197_cse)
                  + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_psp_1_sva[7])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_psp_1_sva[9]) , ((acc_psp_1_sva[11])
                  & (~ (acc_imod_3_sva[1])) & (acc_imod_3_sva[0]))}))))))))) + conv_u2s_10_11({(acc_psp_1_sva[11])
                  , 1'b0 , (acc_psp_1_sva[11]) , 1'b0 , (acc_psp_1_sva[11]) , 1'b0
                  , (acc_psp_1_sva[11]) , 1'b0 , (signext_2_1(acc_psp_1_sva[11]))})))
                  + (conv_s2s_11_12((conv_u2s_10_11(conv_u2u_9_10({(acc_psp_2_sva[10])
                  , 1'b0 , (acc_psp_2_sva[10]) , 1'b0 , (acc_psp_2_sva[10]) , 1'b0
                  , (acc_psp_2_sva[10]) , 1'b0 , (acc_psp_2_sva[10])}) + conv_u2u_8_10(({(acc_psp_2_sva[9])
                  , 1'b0 , (acc_psp_2_sva[9]) , 1'b0 , (acc_psp_2_sva[9]) , 1'b0
                  , (signext_2_1(acc_psp_2_sva[5]))}) + conv_u2u_7_8(conv_u2u_6_7({(acc_psp_2_sva[7])
                  , 1'b0 , (acc_psp_2_sva[5]) , 1'b0 , (signext_2_1(acc_psp_2_sva[11]))})
                  + conv_u2u_5_7(conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_psp_2_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_psp_2_sva[11]) , (~((acc_imod_16_sva[1])
                  & (~ (acc_psp_2_sva[11]))))}))))) + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_psp_2_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_psp_2_sva[11]) , (~
                  (acc_imod_14_sva[2]))})))))) + conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_psp_2_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_psp_2_sva[11]) , (acc_imod_14_sva[1])})))))
                  + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_psp_2_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_psp_2_sva[11]) , (ACC1_acc_107_psp_2_sva[2])}))))))))))
                  + conv_s2s_10_11(conv_s2s_8_10(conv_s2s_6_8(conv_s2s_4_6(conv_s2s_3_4((readslicef_4_3_1((conv_s2s_3_4({1'b1
                  , (acc_psp_2_sva[3]) , 1'b1}) + conv_s2s_2_4({(ACC1_acc_107_psp_2_sva[3])
                  , (acc_psp_2_sva[4])})))) + conv_s2s_2_3(ACC1_acc_116_psp_1_sva[2:1]))
                  + (readslicef_5_4_1((conv_u2s_3_5({(acc_psp_2_sva[3]) , (acc_psp_2_sva[1])
                  , 1'b1}) + conv_s2s_3_5({(ACC1_acc_107_psp_2_sva[3]) , (acc_psp_2_sva[2])
                  , (ACC1_acc_107_psp_2_sva[1])}))))) + conv_u2s_5_6(conv_u2u_4_5({(acc_psp_2_sva[7])
                  , (acc_psp_2_sva[4]) , (signext_2_1(acc_psp_2_sva[11]))}) + conv_u2u_3_5(ACC1_acc_224_cse)))
                  + conv_u2s_7_8({(acc_psp_2_sva[8]) , 1'b0 , (acc_psp_2_sva[8])
                  , 1'b0 , (acc_psp_2_sva[8]) , 1'b0 , (acc_psp_2_sva[8])})) + conv_u2s_8_10(conv_u2u_7_8(signext_7_3({(acc_psp_2_sva[11])
                  , (signext_2_1(acc_psp_2_sva[11]))})) + conv_u2u_6_8(conv_u2u_5_6({(acc_psp_2_sva[6])
                  , 1'b0 , (acc_psp_2_sva[6]) , 1'b0 , (acc_psp_2_sva[6])}) + conv_u2u_4_6(conv_u2u_3_4(ACC1_acc_224_cse)
                  + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_psp_2_sva[7])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_psp_2_sva[9]) , ((acc_psp_2_sva[11])
                  & (~ (acc_imod_16_sva[1])) & (acc_imod_16_sva[0]))})))))))))) +
                  ({(acc_psp_2_sva[11]) , 2'b0 , (acc_psp_2_sva[11]) , 1'b0 , (acc_psp_2_sva[11])
                  , 1'b0 , (acc_psp_2_sva[11]) , (conv_u2u_1_3(acc_psp_2_sva[11])
                  + conv_u2u_2_3(signext_2_1(acc_psp_2_sva[11])))})) + conv_u2s_10_12(conv_u2u_9_10({(acc_psp_1_sva[10])
                  , 1'b0 , (acc_psp_1_sva[10]) , 1'b0 , (acc_psp_1_sva[10]) , 1'b0
                  , (acc_psp_1_sva[10]) , 1'b0 , (acc_psp_1_sva[10])}) + conv_u2u_8_10(({(acc_psp_1_sva[9])
                  , 1'b0 , (acc_psp_1_sva[9]) , 1'b0 , (acc_psp_1_sva[9]) , 1'b0
                  , (signext_2_1(acc_psp_1_sva[5]))}) + conv_u2u_7_8(conv_u2u_6_7({(acc_psp_1_sva[7])
                  , 1'b0 , (acc_psp_1_sva[5]) , 1'b0 , (signext_2_1(acc_psp_1_sva[11]))})
                  + conv_u2u_5_7(conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_psp_1_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_psp_1_sva[11]) , (~((acc_imod_3_sva[1])
                  & (~ (acc_psp_1_sva[11]))))}))))) + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_psp_1_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_psp_1_sva[11]) , (~
                  (acc_imod_2_sva[2]))})))))) + conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_psp_1_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_psp_1_sva[11]) , (acc_imod_2_sva[1])})))))
                  + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_psp_1_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_psp_1_sva[11]) , (ACC1_acc_107_psp_1_sva[2])})))))))))));
              ACC1_acc_250_cse = conv_u2u_2_3(signext_2_1(acc_10_psp_1_sva[11]))
                  + conv_u2u_2_3(signext_2_1(acc_10_psp_1_sva[11]));
              ACC1_acc_277_cse = conv_u2u_2_3(signext_2_1(acc_10_psp_2_sva[11]))
                  + conv_u2u_2_3(signext_2_1(acc_10_psp_2_sva[11]));
              in_2_sva_2 = conv_s2s_11_12(conv_u2s_10_11({(acc_10_psp_1_sva[11])
                  , 8'b0 , (acc_10_psp_1_sva[11])}) + (conv_s2s_10_11(conv_s2s_8_10(conv_s2s_6_8(conv_s2s_4_6(conv_s2s_3_4((readslicef_4_3_1((conv_s2s_3_4({1'b1
                  , (acc_10_psp_1_sva[3]) , 1'b1}) + conv_s2s_2_4({(ACC1_acc_113_psp_1_sva[3])
                  , (acc_10_psp_1_sva[4])})))) + conv_s2s_2_3(ACC1_acc_120_psp_sva[2:1]))
                  + (readslicef_5_4_1((conv_u2s_3_5({(acc_10_psp_1_sva[3]) , (acc_10_psp_1_sva[1])
                  , 1'b1}) + conv_s2s_3_5({(ACC1_acc_113_psp_1_sva[3]) , (acc_10_psp_1_sva[2])
                  , (ACC1_acc_113_psp_1_sva[1])}))))) + conv_u2s_5_6(conv_u2u_4_5({(acc_10_psp_1_sva[7])
                  , (acc_10_psp_1_sva[4]) , (signext_2_1(acc_10_psp_1_sva[11]))})
                  + conv_u2u_3_5(ACC1_acc_250_cse))) + conv_u2s_7_8({(acc_10_psp_1_sva[8])
                  , 1'b0 , (acc_10_psp_1_sva[8]) , 1'b0 , (acc_10_psp_1_sva[8]) ,
                  1'b0 , (acc_10_psp_1_sva[8])})) + conv_u2s_8_10(conv_u2u_7_8(signext_7_3({(acc_10_psp_1_sva[11])
                  , (signext_2_1(acc_10_psp_1_sva[11]))})) + conv_u2u_6_8(conv_u2u_5_6({(acc_10_psp_1_sva[6])
                  , 1'b0 , (acc_10_psp_1_sva[6]) , 1'b0 , (acc_10_psp_1_sva[6])})
                  + conv_u2u_4_6(conv_u2u_3_4(ACC1_acc_250_cse) + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_10_psp_1_sva[7])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_10_psp_1_sva[9]) , ((acc_10_psp_1_sva[11])
                  & (~ (acc_imod_11_sva[1])) & (acc_imod_11_sva[0]))}))))))))) +
                  conv_u2s_10_11({(acc_10_psp_1_sva[11]) , 1'b0 , (acc_10_psp_1_sva[11])
                  , 1'b0 , (acc_10_psp_1_sva[11]) , 1'b0 , (acc_10_psp_1_sva[11])
                  , 1'b0 , (signext_2_1(acc_10_psp_1_sva[11]))}))) + (conv_s2s_11_12((conv_u2s_10_11(conv_u2u_9_10({(acc_10_psp_2_sva[10])
                  , 1'b0 , (acc_10_psp_2_sva[10]) , 1'b0 , (acc_10_psp_2_sva[10])
                  , 1'b0 , (acc_10_psp_2_sva[10]) , 1'b0 , (acc_10_psp_2_sva[10])})
                  + conv_u2u_8_10(({(acc_10_psp_2_sva[9]) , 1'b0 , (acc_10_psp_2_sva[9])
                  , 1'b0 , (acc_10_psp_2_sva[9]) , 1'b0 , (signext_2_1(acc_10_psp_2_sva[5]))})
                  + conv_u2u_7_8(conv_u2u_6_7({(acc_10_psp_2_sva[7]) , 1'b0 , (acc_10_psp_2_sva[5])
                  , 1'b0 , (signext_2_1(acc_10_psp_2_sva[11]))}) + conv_u2u_5_7(conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_10_psp_2_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_10_psp_2_sva[11]) ,
                  (~((acc_imod_24_sva[1]) & (~ (acc_10_psp_2_sva[11]))))}))))) +
                  conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_10_psp_2_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_10_psp_2_sva[11]) ,
                  (~ (acc_imod_22_sva[2]))})))))) + conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_10_psp_2_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_10_psp_2_sva[11]) ,
                  (acc_imod_22_sva[1])}))))) + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_10_psp_2_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_10_psp_2_sva[11]) ,
                  (ACC1_acc_113_psp_2_sva[2])})))))))))) + conv_s2s_10_11(conv_s2s_8_10(conv_s2s_6_8(conv_s2s_4_6(conv_s2s_3_4((readslicef_4_3_1((conv_s2s_3_4({1'b1
                  , (acc_10_psp_2_sva[3]) , 1'b1}) + conv_s2s_2_4({(ACC1_acc_113_psp_2_sva[3])
                  , (acc_10_psp_2_sva[4])})))) + conv_s2s_2_3(ACC1_acc_120_psp_1_sva[2:1]))
                  + (readslicef_5_4_1((conv_u2s_3_5({(acc_10_psp_2_sva[3]) , (acc_10_psp_2_sva[1])
                  , 1'b1}) + conv_s2s_3_5({(ACC1_acc_113_psp_2_sva[3]) , (acc_10_psp_2_sva[2])
                  , (ACC1_acc_113_psp_2_sva[1])}))))) + conv_u2s_5_6(conv_u2u_4_5({(acc_10_psp_2_sva[7])
                  , (acc_10_psp_2_sva[4]) , (signext_2_1(acc_10_psp_2_sva[11]))})
                  + conv_u2u_3_5(ACC1_acc_277_cse))) + conv_u2s_7_8({(acc_10_psp_2_sva[8])
                  , 1'b0 , (acc_10_psp_2_sva[8]) , 1'b0 , (acc_10_psp_2_sva[8]) ,
                  1'b0 , (acc_10_psp_2_sva[8])})) + conv_u2s_8_10(conv_u2u_7_8(signext_7_3({(acc_10_psp_2_sva[11])
                  , (signext_2_1(acc_10_psp_2_sva[11]))})) + conv_u2u_6_8(conv_u2u_5_6({(acc_10_psp_2_sva[6])
                  , 1'b0 , (acc_10_psp_2_sva[6]) , 1'b0 , (acc_10_psp_2_sva[6])})
                  + conv_u2u_4_6(conv_u2u_3_4(ACC1_acc_277_cse) + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_10_psp_2_sva[7])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_10_psp_2_sva[9]) , ((acc_10_psp_2_sva[11])
                  & (~ (acc_imod_24_sva[1])) & (acc_imod_24_sva[0]))})))))))))) +
                  ({(acc_10_psp_2_sva[11]) , 2'b0 , (acc_10_psp_2_sva[11]) , 1'b0
                  , (acc_10_psp_2_sva[11]) , 1'b0 , (acc_10_psp_2_sva[11]) , (conv_u2u_1_3(acc_10_psp_2_sva[11])
                  + conv_u2u_2_3(signext_2_1(acc_10_psp_2_sva[11])))})) + conv_u2s_10_12(conv_u2u_9_10({(acc_10_psp_1_sva[10])
                  , 1'b0 , (acc_10_psp_1_sva[10]) , 1'b0 , (acc_10_psp_1_sva[10])
                  , 1'b0 , (acc_10_psp_1_sva[10]) , 1'b0 , (acc_10_psp_1_sva[10])})
                  + conv_u2u_8_10(({(acc_10_psp_1_sva[9]) , 1'b0 , (acc_10_psp_1_sva[9])
                  , 1'b0 , (acc_10_psp_1_sva[9]) , 1'b0 , (signext_2_1(acc_10_psp_1_sva[5]))})
                  + conv_u2u_7_8(conv_u2u_6_7({(acc_10_psp_1_sva[7]) , 1'b0 , (acc_10_psp_1_sva[5])
                  , 1'b0 , (signext_2_1(acc_10_psp_1_sva[11]))}) + conv_u2u_5_7(conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_10_psp_1_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_10_psp_1_sva[11]) ,
                  (~((acc_imod_11_sva[1]) & (~ (acc_10_psp_1_sva[11]))))}))))) +
                  conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_10_psp_1_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_10_psp_1_sva[11]) ,
                  (~ (acc_imod_10_sva[2]))})))))) + conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_10_psp_1_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_10_psp_1_sva[11]) ,
                  (acc_imod_10_sva[1])}))))) + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(acc_10_psp_1_sva[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(acc_10_psp_1_sva[11]) ,
                  (ACC1_acc_113_psp_1_sva[2])})))))))))));
              acc_imod_6_lpi_1_dfm_sg1 = acc_imod_6_sva[2:1];
              acc_imod_7_lpi_1_dfm = readslicef_3_2_1((({1'b1 , (acc_imod_6_sva[0])
                  , 1'b1}) + conv_u2s_2_3({(~ (acc_imod_6_sva[1])) , (~ (acc_imod_6_sva[2]))})));
              regs_regs_0_sva_dfm = regs_regs_0_sva_1;
              regs_regs_1_sva_dfm = regs_regs_0_sva;
              regs_regs_2_lpi_1_dfm_1 = regs_regs_1_sva[29:0];
              regs_regs_2_lpi_1_dfm_sg2 = regs_regs_1_sva[89:60];
              ACC1_acc_118_psp_lpi_1_dfm_sg1 = ACC1_acc_118_psp_sva[2:1];
              ACC1_acc_125_psp_lpi_1_dfm = ACC1_acc_125_psp_sva;
              ACC1_acc_110_psp_1_lpi_1_dfm_sg1 = ACC1_acc_110_psp_1_sva[3:1];
            end
            else begin
              regs_regs_0_sva_dfm = regs_regs_0_sva;
              regs_regs_1_sva_dfm = regs_regs_1_sva;
            end
            i_6_lpi_1_dfm = i_6_sva_1 & (signext_2_1(~ exit_FRAME_for_lpi_1_dfm));
            acc_imod_18_lpi_1_dfm_sg1 = MUX_v_2_2_2({acc_imod_18_lpi_1_dfm_sg1 ,
                (acc_imod_18_sva[2:1])}, exit_FRAME_for_lpi_1_dfm);
            acc_imod_20_lpi_1_dfm = MUX_v_2_2_2({acc_imod_20_lpi_1_dfm , acc_imod_20_sva},
                exit_FRAME_for_lpi_1_dfm);
            ACC1_acc_118_psp_1_lpi_1_dfm_sg1 = MUX_v_2_2_2({ACC1_acc_118_psp_1_lpi_1_dfm_sg1
                , (ACC1_acc_118_psp_1_sva[2:1])}, exit_FRAME_for_lpi_1_dfm);
            ACC1_acc_125_psp_1_lpi_1_dfm = MUX_v_12_2_2({ACC1_acc_125_psp_1_lpi_1_dfm
                , ACC1_acc_125_psp_1_sva}, exit_FRAME_for_lpi_1_dfm);
            ACC1_acc_110_psp_2_lpi_1_dfm_sg1 = MUX_v_3_2_2({ACC1_acc_110_psp_2_lpi_1_dfm_sg1
                , (ACC1_acc_110_psp_2_sva[3:1])}, exit_FRAME_for_lpi_1_dfm);
            FRAME_for_nor_cse = ~((i_6_lpi_1_dfm[1]) | (i_6_lpi_1_dfm[0]));
            FRAME_for_slc_YMATRIX_rom_11_psp_sva = (~((i_6_lpi_1_dfm[0]) & (~ (i_6_lpi_1_dfm[1]))))
                | FRAME_for_nor_cse | ((i_6_lpi_1_dfm[1]) & (~ (i_6_lpi_1_dfm[0])));
            FRAME_for_slc_XMATRIX_rom_10_psp_sva_1 = (~((~ (i_6_lpi_1_dfm[1])) &
                (i_6_lpi_1_dfm[0]))) | FRAME_for_nor_cse;
            i_6_sva_1 = i_6_lpi_1_dfm + 2'b1;
            exit_FRAME_for_sva_1 = ~ (readslicef_3_1_2((({1'b1 , i_6_sva_1}) + 3'b1)));
            if ( exit_FRAME_for_sva_1 ) begin
              ACC1_acc_341_itm = (conv_s2s_26_13(conv_u2s_2_13(conv_u2u_1_2(ACC1_acc_125_psp_lpi_1_dfm[11])
                  + conv_u2u_1_2(ACC1_acc_125_psp_1_lpi_1_dfm[11])) * 13'b1101000000001)
                  + conv_u2s_10_13((conv_u2u_9_10({conv_u2u_12_6(conv_u2u_2_6(conv_u2u_1_2(ACC1_acc_125_psp_lpi_1_dfm[8])
                  + conv_u2u_1_2(ACC1_acc_125_psp_1_lpi_1_dfm[8])) * 6'b10101) ,
                  (ACC1_acc_125_psp_lpi_1_dfm[3]) , (signext_2_1(ACC1_acc_125_psp_lpi_1_dfm[11]))})
                  + conv_u2u_8_10(conv_u2u_16_8(conv_u2u_2_8(conv_u2u_1_2(ACC1_acc_125_psp_lpi_1_dfm[7])
                  + conv_u2u_1_2(ACC1_acc_125_psp_1_lpi_1_dfm[7])) * 8'b1010101)
                  + conv_u2u_7_8(conv_u2u_6_7(conv_u2u_12_6(conv_u2u_2_6(conv_u2u_1_2(ACC1_acc_125_psp_lpi_1_dfm[5])
                  + conv_u2u_1_2(ACC1_acc_125_psp_1_lpi_1_dfm[5])) * 6'b10101)) +
                  conv_u2u_6_7({(ACC1_acc_125_psp_lpi_1_dfm[6]) , 1'b0 , (ACC1_acc_125_psp_lpi_1_dfm[4])
                  , 1'b0 , (signext_2_1(ACC1_acc_125_psp_lpi_1_dfm[11]))})))) + conv_u2u_8_10((conv_u2u_7_8(signext_7_3({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , (signext_2_1(ACC1_acc_125_psp_1_lpi_1_dfm[11]))})) + conv_u2u_6_8(conv_u2u_5_6(conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_lpi_1_dfm[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_lpi_1_dfm[11])
                  , (acc_imod_18_lpi_1_dfm_sg1[0])}))))) + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_lpi_1_dfm[4])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_lpi_1_dfm[11])
                  , (ACC1_acc_110_psp_2_lpi_1_dfm_sg1[2])})))))) + conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , (ACC1_acc_110_psp_2_lpi_1_dfm_sg1[0])}))))) + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , ((ACC1_acc_125_psp_lpi_1_dfm[11]) & (~ (acc_imod_7_lpi_1_dfm[1]))
                  & (acc_imod_7_lpi_1_dfm[0]))}))))))) + conv_u2u_5_6(conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[6])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[8])
                  , (~((acc_imod_7_lpi_1_dfm[1]) & (~ (ACC1_acc_125_psp_lpi_1_dfm[11]))))})))))
                  + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[10])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , (acc_imod_6_lpi_1_dfm_sg1[0])})))))) + conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , (ACC1_acc_110_psp_1_lpi_1_dfm_sg1[2])}))))) + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , (ACC1_acc_110_psp_1_lpi_1_dfm_sg1[1])}))))))))) + conv_u2u_7_8(conv_u2u_6_7(conv_u2u_5_6(conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , (ACC1_acc_110_psp_1_lpi_1_dfm_sg1[0])}))))) + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2(ACC1_acc_125_psp_1_lpi_1_dfm[4:3]))))))
                  + conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  , (ACC1_acc_125_psp_1_lpi_1_dfm[2])}))))) + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_lpi_1_dfm[6])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_lpi_1_dfm[8])
                  , (ACC1_acc_125_psp_1_lpi_1_dfm[1])}))))))) + conv_u2u_5_6(conv_u2u_4_5(conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_lpi_1_dfm[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_lpi_1_dfm[11])
                  , (ACC1_acc_125_psp_1_lpi_1_dfm[0])}))))) + conv_u2u_3_4(readslicef_4_3_1((conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_lpi_1_dfm[11])
                  , 1'b1})) + conv_u2u_3_4(signext_3_2({(ACC1_acc_125_psp_lpi_1_dfm[11])
                  , (ACC1_acc_125_psp_lpi_1_dfm[3])})))))) + conv_u2u_4_5(readslicef_5_4_1((conv_u2u_4_5({(readslicef_4_3_1((conv_u2u_3_4({(ACC1_acc_125_psp_lpi_1_dfm[2])
                  , (ACC1_acc_125_psp_lpi_1_dfm[0]) , 1'b1}) + conv_u2u_3_4({(ACC1_acc_125_psp_1_lpi_1_dfm[2])
                  , (ACC1_acc_125_psp_lpi_1_dfm[1]) , (ACC1_acc_125_psp_lpi_1_dfm[2])}))))
                  , 1'b1}) + conv_u2u_4_5({(~ (ACC1_acc_110_psp_1_lpi_1_dfm_sg1[2]))
                  , 1'b1 , (~ (acc_imod_6_lpi_1_dfm_sg1[1])) , ((ACC1_acc_125_psp_1_lpi_1_dfm[11])
                  & (~ (acc_imod_20_lpi_1_dfm[1])) & (acc_imod_20_lpi_1_dfm[0]))}))))))
                  + conv_u2u_4_7((readslicef_5_4_1((conv_u2u_4_5({(~ (ACC1_acc_110_psp_2_lpi_1_dfm_sg1[2]))
                  , 1'b1 , (~ (acc_imod_18_lpi_1_dfm_sg1[1])) , 1'b1}) + conv_s2u_3_5({ACC1_acc_118_psp_lpi_1_dfm_sg1
                  , (~((acc_imod_20_lpi_1_dfm[1]) & (~ (ACC1_acc_125_psp_1_lpi_1_dfm[11]))))}))))
                  + (readslicef_5_4_1((conv_u2s_3_5(signext_3_2({(ACC1_acc_125_psp_lpi_1_dfm[11])
                  , 1'b1})) + conv_s2s_3_5({ACC1_acc_118_psp_1_lpi_1_dfm_sg1 , (ACC1_acc_110_psp_2_lpi_1_dfm_sg1[1])})))))))))
                  + (conv_s2s_11_13(conv_u2s_10_12(conv_u2s_20_11(conv_u2u_2_10(conv_u2u_1_2(ACC1_acc_125_psp_lpi_1_dfm[9])
                  + conv_u2u_1_2(ACC1_acc_125_psp_1_lpi_1_dfm[9])) * 10'b101010101))
                  + conv_s2s_9_11(conv_s2s_7_9(conv_u2s_6_7({(ACC1_acc_125_psp_1_lpi_1_dfm[6])
                  , 1'b0 , (ACC1_acc_125_psp_lpi_1_dfm[6]) , 1'b0 , (signext_2_1(ACC1_acc_125_psp_lpi_1_dfm[11]))})
                  + conv_s2s_5_7(({(conv_u2u_1_2(ACC1_acc_125_psp_1_lpi_1_dfm[4])
                  + conv_u2u_1_2(ACC1_acc_125_psp_1_lpi_1_dfm[6])) , (conv_u2u_2_3(signext_2_1(ACC1_acc_125_psp_lpi_1_dfm[10]))
                  + conv_u2u_2_3(signext_2_1(ACC1_acc_125_psp_lpi_1_dfm[11])))})
                  + ({3'b100 , (signext_2_1(ACC1_acc_125_psp_lpi_1_dfm[11]))})))
                  + conv_u2s_7_9(signext_7_3({(ACC1_acc_125_psp_lpi_1_dfm[11]) ,
                  (signext_2_1(ACC1_acc_125_psp_lpi_1_dfm[11]))})))) + conv_u2s_11_13({conv_u2u_16_8(conv_u2u_2_8(conv_u2u_1_2(ACC1_acc_125_psp_lpi_1_dfm[10])
                  + conv_u2u_1_2(ACC1_acc_125_psp_1_lpi_1_dfm[10])) * 8'b1010101)
                  , (ACC1_acc_125_psp_1_lpi_1_dfm[3]) , (signext_2_1(ACC1_acc_125_psp_lpi_1_dfm[11]))}));
              FRAME_p_1_sva_1 = FRAME_p_1_lpi_1_dfm + 19'b1;
              exit_FRAME_lpi_1_dfm_1 = ~ (readslicef_8_1_7((conv_u2s_7_8(FRAME_p_1_sva_1[18:12])
                  + 8'b10110101)));
            end
            else begin
              exit_FRAME_lpi_1_dfm_1 = exit_FRAME_lpi_1_dfm_1 & (~ exit_FRAME_for_lpi_1_dfm);
            end
            exit_FRAME_for_lpi_1_dfm_2 = exit_FRAME_for_sva_1;
            regs_regs_0_sva = regs_regs_0_sva_dfm;
            regs_regs_1_sva = regs_regs_1_sva_dfm;
            FRAME_p_1_lpi_1 = MUX_v_19_2_2({FRAME_p_1_lpi_1_dfm , FRAME_p_1_sva_1},
                exit_FRAME_for_sva_1);
            exit_FRAME_1_sva = exit_FRAME_for_sva_1 & exit_FRAME_lpi_1_dfm_1;
            exit_FRAME_for_lpi_1_dfm_3 = exit_FRAME_for_lpi_1_dfm;
            regs_operator_10_mux_nl = MUX_v_10_4_2({(regs_regs_0_sva_dfm[19:10])
                , (regs_regs_1_sva_dfm[19:10]) , (regs_regs_2_lpi_1_dfm_1[19:10])
                , 10'b0}, i_6_lpi_1_dfm);
            regs_operator_11_mux_nl = MUX_v_10_4_2({(regs_regs_0_sva_dfm[9:0]) ,
                (regs_regs_1_sva_dfm[9:0]) , (regs_regs_2_lpi_1_dfm_1[9:0]) , 10'b0},
                i_6_lpi_1_dfm);
            regs_operator_9_mux_nl = MUX_v_10_4_2({(regs_regs_0_sva_dfm[29:20]) ,
                (regs_regs_1_sva_dfm[29:20]) , (regs_regs_2_lpi_1_dfm_1[29:20]) ,
                10'b0}, i_6_lpi_1_dfm);
            FRAME_for_acc_24_itm_1 = (conv_s2s_12_13(conv_s2s_24_12(conv_s2s_10_12(regs_operator_10_mux_nl)
                * conv_s2s_2_12({1'b1 , FRAME_for_slc_YMATRIX_rom_11_psp_sva})))
                + conv_s2s_12_13(conv_s2s_24_12(conv_s2s_10_12(regs_operator_11_mux_nl)
                * conv_s2s_2_12({1'b1 , FRAME_for_slc_YMATRIX_rom_11_psp_sva}))))
                + conv_s2s_12_13(conv_s2s_24_12(conv_s2s_10_12(regs_operator_9_mux_nl)
                * conv_s2s_2_12({1'b1 , FRAME_for_slc_YMATRIX_rom_11_psp_sva})));
            FRAME_for_slc_in_0_sva_itm_1 = in_0_sva_2;
            regs_operator_16_mux_nl = MUX_v_10_4_2({(regs_regs_0_sva_dfm[79:70])
                , (regs_regs_1_sva_dfm[79:70]) , (regs_regs_2_lpi_1_dfm_sg2[19:10])
                , 10'b0}, i_6_lpi_1_dfm);
            regs_operator_17_mux_nl = MUX_v_10_4_2({(regs_regs_0_sva_dfm[69:60])
                , (regs_regs_1_sva_dfm[69:60]) , (regs_regs_2_lpi_1_dfm_sg2[9:0])
                , 10'b0}, i_6_lpi_1_dfm);
            regs_operator_15_mux_nl = MUX_v_10_4_2({(regs_regs_0_sva_dfm[89:80])
                , (regs_regs_1_sva_dfm[89:80]) , (regs_regs_2_lpi_1_dfm_sg2[29:20])
                , 10'b0}, i_6_lpi_1_dfm);
            FRAME_for_acc_26_itm_1 = (conv_s2s_11_12(conv_s2s_22_11(conv_s2s_10_11(regs_operator_16_mux_nl)
                * conv_s2s_2_11({FRAME_for_nor_cse , FRAME_for_slc_XMATRIX_rom_10_psp_sva_1})))
                + conv_s2s_11_12(conv_s2s_22_11(conv_s2s_10_11(regs_operator_17_mux_nl)
                * conv_s2s_2_11({FRAME_for_nor_cse , FRAME_for_slc_XMATRIX_rom_10_psp_sva_1}))))
                + conv_s2s_11_12(conv_s2s_22_11(conv_s2s_10_11(regs_operator_15_mux_nl)
                * conv_s2s_2_11({FRAME_for_nor_cse , FRAME_for_slc_XMATRIX_rom_10_psp_sva_1})));
            FRAME_for_slc_in_2_sva_itm_1 = in_2_sva_2;
            ACC1_acc_341_itm_1 = ACC1_acc_341_itm;
            exit_FRAME_for_sva_1_st_1 = exit_FRAME_for_sva_1;
            main_stage_0_2 = 1'b1;
          end
        end
      end
    end
    FRAME_for_slc_XMATRIX_rom_10_psp_sva_1 = 1'b0;
    FRAME_for_nor_cse = 1'b0;
    ACC1_acc_277_cse = 3'b0;
    ACC1_acc_250_cse = 3'b0;
    ACC1_acc_224_cse = 3'b0;
    ACC1_acc_197_cse = 3'b0;
    ACC1_acc_110_psp_2_lpi_1_dfm_sg1 = 3'b0;
    ACC1_acc_118_psp_1_lpi_1_dfm_sg1 = 2'b0;
    acc_imod_18_lpi_1_dfm_sg1 = 2'b0;
    ACC1_acc_110_psp_1_lpi_1_dfm_sg1 = 3'b0;
    ACC1_acc_118_psp_lpi_1_dfm_sg1 = 2'b0;
    regs_regs_2_lpi_1_dfm_1 = 30'b0;
    regs_regs_2_lpi_1_dfm_sg2 = 30'b0;
    acc_imod_6_lpi_1_dfm_sg1 = 2'b0;
    in_2_sva_2 = 12'b0;
    in_0_sva_2 = 12'b0;
    main_stage_0_2 = 1'b0;
    exit_FRAME_for_sva_1_st_1 = 1'b0;
    ACC1_acc_341_itm_1 = 13'b0;
    ACC1_acc_341_itm = 13'b0;
    FRAME_for_slc_in_2_sva_itm_1 = 12'b0;
    FRAME_for_acc_26_itm_1 = 12'b0;
    FRAME_for_slc_in_0_sva_itm_1 = 12'b0;
    FRAME_for_acc_24_itm_1 = 13'b0;
    exit_FRAME_for_lpi_1_dfm_3 = 1'b0;
    exit_FRAME_for_lpi_1_dfm_2 = 1'b0;
    exit_FRAME_lpi_1_dfm_1 = 1'b0;
    FRAME_p_1_sva_1 = 19'b0;
    FRAME_acc_2_psp_sva = 12'b0;
    acc_imod_12_sva = 6'b0;
    intensity_2_sg1_sva = 15'b0;
    exit_FRAME_for_sva_1 = 1'b0;
    i_6_sva_1 = 2'b0;
    in_2_sva_1 = 16'b0;
    in_0_sva_1 = 16'b0;
    FRAME_for_slc_YMATRIX_rom_11_psp_sva = 1'b0;
    ACC1_acc_125_psp_1_lpi_1_dfm = 12'b0;
    acc_imod_20_lpi_1_dfm = 2'b0;
    i_6_lpi_1_dfm = 2'b0;
    ACC1_acc_125_psp_lpi_1_dfm = 12'b0;
    regs_regs_1_sva_dfm = 90'b0;
    regs_regs_0_sva_dfm = 90'b0;
    acc_imod_7_lpi_1_dfm = 2'b0;
    acc_imod_11_sva = 2'b0;
    acc_imod_10_sva = 3'b0;
    ACC1_acc_120_psp_sva = 3'b0;
    ACC1_acc_113_psp_1_sva = 4'b0;
    acc_10_psp_1_sva = 12'b0;
    acc_imod_6_sva = 3'b0;
    ACC1_acc_118_psp_sva = 3'b0;
    ACC1_acc_110_psp_1_sva = 4'b0;
    ACC1_acc_125_psp_sva = 12'b0;
    acc_imod_3_sva = 2'b0;
    acc_imod_2_sva = 3'b0;
    ACC1_acc_116_psp_sva = 3'b0;
    ACC1_acc_107_psp_1_sva = 4'b0;
    acc_psp_1_sva = 12'b0;
    acc_imod_24_sva = 2'b0;
    acc_imod_22_sva = 3'b0;
    ACC1_acc_120_psp_1_sva = 3'b0;
    ACC1_acc_113_psp_2_sva = 4'b0;
    acc_10_psp_2_sva = 12'b0;
    acc_imod_20_sva = 2'b0;
    acc_imod_18_sva = 3'b0;
    ACC1_acc_118_psp_1_sva = 3'b0;
    ACC1_acc_110_psp_2_sva = 4'b0;
    ACC1_acc_125_psp_1_sva = 12'b0;
    acc_imod_16_sva = 2'b0;
    acc_imod_14_sva = 3'b0;
    ACC1_acc_116_psp_1_sva = 3'b0;
    ACC1_acc_107_psp_2_sva = 4'b0;
    acc_psp_2_sva = 12'b0;
    regs_regs_0_sva_1 = 90'b0;
    exit_FRAME_for_lpi_1_dfm = 1'b0;
    FRAME_p_1_lpi_1_dfm = 19'b0;
    exit_FRAME_1_sva = 1'b0;
    regs_regs_0_sva = 90'b0;
    regs_regs_1_sva = 90'b0;
    FRAME_p_1_lpi_1 = 19'b0;
    vout_rsc_mgc_out_stdreg_d <= 30'b0;
  end


  function [15:0] MUX_v_16_2_2;
    input [31:0] inputs;
    input [0:0] sel;
    reg [15:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[31:16];
      end
      1'b1 : begin
        result = inputs[15:0];
      end
      default : begin
        result = inputs[31:16];
      end
    endcase
    MUX_v_16_2_2 = result;
  end
  endfunction


  function [14:0] readslicef_16_15_1;
    input [15:0] vector;
    reg [15:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_16_15_1 = tmp[14:0];
  end
  endfunction


  function [0:0] readslicef_5_1_4;
    input [4:0] vector;
    reg [4:0] tmp;
  begin
    tmp = vector >> 4;
    readslicef_5_1_4 = tmp[0:0];
  end
  endfunction


  function [2:0] signext_3_1;
    input [0:0] vector;
  begin
    signext_3_1= {{2{vector[0]}}, vector};
  end
  endfunction


  function [10:0] signext_11_9;
    input [8:0] vector;
  begin
    signext_11_9= {{2{vector[8]}}, vector};
  end
  endfunction


  function [18:0] signext_19_1;
    input [0:0] vector;
  begin
    signext_19_1= {{18{vector[0]}}, vector};
  end
  endfunction


  function [3:0] readslicef_5_4_1;
    input [4:0] vector;
    reg [4:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_5_4_1 = tmp[3:0];
  end
  endfunction


  function [2:0] readslicef_4_3_1;
    input [3:0] vector;
    reg [3:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_4_3_1 = tmp[2:0];
  end
  endfunction


  function [1:0] readslicef_3_2_1;
    input [2:0] vector;
    reg [2:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_3_2_1 = tmp[1:0];
  end
  endfunction


  function [1:0] signext_2_1;
    input [0:0] vector;
  begin
    signext_2_1= {{1{vector[0]}}, vector};
  end
  endfunction


  function [6:0] signext_7_3;
    input [2:0] vector;
  begin
    signext_7_3= {{4{vector[2]}}, vector};
  end
  endfunction


  function [2:0] signext_3_2;
    input [1:0] vector;
  begin
    signext_3_2= {{1{vector[1]}}, vector};
  end
  endfunction


  function [1:0] MUX_v_2_2_2;
    input [3:0] inputs;
    input [0:0] sel;
    reg [1:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[3:2];
      end
      1'b1 : begin
        result = inputs[1:0];
      end
      default : begin
        result = inputs[3:2];
      end
    endcase
    MUX_v_2_2_2 = result;
  end
  endfunction


  function [11:0] MUX_v_12_2_2;
    input [23:0] inputs;
    input [0:0] sel;
    reg [11:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[23:12];
      end
      1'b1 : begin
        result = inputs[11:0];
      end
      default : begin
        result = inputs[23:12];
      end
    endcase
    MUX_v_12_2_2 = result;
  end
  endfunction


  function [2:0] MUX_v_3_2_2;
    input [5:0] inputs;
    input [0:0] sel;
    reg [2:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[5:3];
      end
      1'b1 : begin
        result = inputs[2:0];
      end
      default : begin
        result = inputs[5:3];
      end
    endcase
    MUX_v_3_2_2 = result;
  end
  endfunction


  function [0:0] readslicef_3_1_2;
    input [2:0] vector;
    reg [2:0] tmp;
  begin
    tmp = vector >> 2;
    readslicef_3_1_2 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_8_1_7;
    input [7:0] vector;
    reg [7:0] tmp;
  begin
    tmp = vector >> 7;
    readslicef_8_1_7 = tmp[0:0];
  end
  endfunction


  function [18:0] MUX_v_19_2_2;
    input [37:0] inputs;
    input [0:0] sel;
    reg [18:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[37:19];
      end
      1'b1 : begin
        result = inputs[18:0];
      end
      default : begin
        result = inputs[37:19];
      end
    endcase
    MUX_v_19_2_2 = result;
  end
  endfunction


  function [9:0] MUX_v_10_4_2;
    input [39:0] inputs;
    input [1:0] sel;
    reg [9:0] result;
  begin
    case (sel)
      2'b00 : begin
        result = inputs[39:30];
      end
      2'b01 : begin
        result = inputs[29:20];
      end
      2'b10 : begin
        result = inputs[19:10];
      end
      2'b11 : begin
        result = inputs[9:0];
      end
      default : begin
        result = inputs[39:30];
      end
    endcase
    MUX_v_10_4_2 = result;
  end
  endfunction


  function  [15:0] conv_s2u_13_16 ;
    input signed [12:0]  vector ;
  begin
    conv_s2u_13_16 = {{3{vector[12]}}, vector};
  end
  endfunction


  function  [15:0] conv_s2u_12_16 ;
    input signed [11:0]  vector ;
  begin
    conv_s2u_12_16 = {{4{vector[11]}}, vector};
  end
  endfunction


  function signed [15:0] conv_s2s_13_16 ;
    input signed [12:0]  vector ;
  begin
    conv_s2s_13_16 = {{3{vector[12]}}, vector};
  end
  endfunction


  function  [5:0] conv_u2u_5_6 ;
    input [4:0]  vector ;
  begin
    conv_u2u_5_6 = {1'b0, vector};
  end
  endfunction


  function  [4:0] conv_u2u_4_5 ;
    input [3:0]  vector ;
  begin
    conv_u2u_4_5 = {1'b0, vector};
  end
  endfunction


  function  [3:0] conv_u2u_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2u_3_4 = {1'b0, vector};
  end
  endfunction


  function  [3:0] conv_u2u_2_4 ;
    input [1:0]  vector ;
  begin
    conv_u2u_2_4 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [5:0] conv_u2u_4_6 ;
    input [3:0]  vector ;
  begin
    conv_u2u_4_6 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [12:0] conv_u2s_11_13 ;
    input [10:0]  vector ;
  begin
    conv_u2s_11_13 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [11:0] conv_u2s_22_12 ;
    input [21:0]  vector ;
  begin
    conv_u2s_22_12 = vector[11:0];
  end
  endfunction


  function  [10:0] conv_u2u_2_11 ;
    input [1:0]  vector ;
  begin
    conv_u2u_2_11 = {{9{1'b0}}, vector};
  end
  endfunction


  function signed [11:0] conv_s2s_10_12 ;
    input signed [9:0]  vector ;
  begin
    conv_s2s_10_12 = {{2{vector[9]}}, vector};
  end
  endfunction


  function signed [10:0] conv_u2s_9_11 ;
    input [8:0]  vector ;
  begin
    conv_u2s_9_11 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [9:0] conv_u2s_18_10 ;
    input [17:0]  vector ;
  begin
    conv_u2s_18_10 = vector[9:0];
  end
  endfunction


  function  [8:0] conv_u2u_3_9 ;
    input [2:0]  vector ;
  begin
    conv_u2u_3_9 = {{6{1'b0}}, vector};
  end
  endfunction


  function signed [9:0] conv_s2s_8_10 ;
    input signed [7:0]  vector ;
  begin
    conv_s2s_8_10 = {{2{vector[7]}}, vector};
  end
  endfunction


  function signed [7:0] conv_u2s_6_8 ;
    input [5:0]  vector ;
  begin
    conv_u2s_6_8 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [7:0] conv_s2s_5_8 ;
    input signed [4:0]  vector ;
  begin
    conv_s2s_5_8 = {{3{vector[4]}}, vector};
  end
  endfunction


  function signed [4:0] conv_u2s_4_5 ;
    input [3:0]  vector ;
  begin
    conv_u2s_4_5 = {1'b0, vector};
  end
  endfunction


  function  [4:0] conv_u2u_3_5 ;
    input [2:0]  vector ;
  begin
    conv_u2u_3_5 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [11:0] conv_u2u_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2u_11_12 = {1'b0, vector};
  end
  endfunction


  function signed [11:0] conv_s2s_11_12 ;
    input signed [10:0]  vector ;
  begin
    conv_s2s_11_12 = {vector[10], vector};
  end
  endfunction


  function signed [10:0] conv_s2s_10_11 ;
    input signed [9:0]  vector ;
  begin
    conv_s2s_10_11 = {vector[9], vector};
  end
  endfunction


  function signed [4:0] conv_s2s_4_5 ;
    input signed [3:0]  vector ;
  begin
    conv_s2s_4_5 = {vector[3], vector};
  end
  endfunction


  function signed [3:0] conv_s2s_2_4 ;
    input signed [1:0]  vector ;
  begin
    conv_s2s_2_4 = {{2{vector[1]}}, vector};
  end
  endfunction


  function signed [3:0] conv_u2s_2_4 ;
    input [1:0]  vector ;
  begin
    conv_u2s_2_4 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [3:0] conv_u2s_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_4 = {1'b0, vector};
  end
  endfunction


  function  [2:0] conv_u2u_2_3 ;
    input [1:0]  vector ;
  begin
    conv_u2u_2_3 = {1'b0, vector};
  end
  endfunction


  function signed [2:0] conv_u2s_2_3 ;
    input [1:0]  vector ;
  begin
    conv_u2s_2_3 = {1'b0, vector};
  end
  endfunction


  function signed [2:0] conv_s2s_1_3 ;
    input signed [0:0]  vector ;
  begin
    conv_s2s_1_3 = {{2{vector[0]}}, vector};
  end
  endfunction


  function signed [3:0] conv_s2s_3_4 ;
    input signed [2:0]  vector ;
  begin
    conv_s2s_3_4 = {vector[2], vector};
  end
  endfunction


  function  [11:0] conv_s2u_11_12 ;
    input signed [10:0]  vector ;
  begin
    conv_s2u_11_12 = {vector[10], vector};
  end
  endfunction


  function signed [4:0] conv_u2s_3_5 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_5 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [4:0] conv_s2s_3_5 ;
    input signed [2:0]  vector ;
  begin
    conv_s2s_3_5 = {{2{vector[2]}}, vector};
  end
  endfunction


  function  [11:0] conv_s2u_10_12 ;
    input signed [9:0]  vector ;
  begin
    conv_s2u_10_12 = {{2{vector[9]}}, vector};
  end
  endfunction


  function signed [10:0] conv_u2s_10_11 ;
    input [9:0]  vector ;
  begin
    conv_u2s_10_11 = {1'b0, vector};
  end
  endfunction


  function signed [7:0] conv_s2s_6_8 ;
    input signed [5:0]  vector ;
  begin
    conv_s2s_6_8 = {{2{vector[5]}}, vector};
  end
  endfunction


  function signed [5:0] conv_s2s_4_6 ;
    input signed [3:0]  vector ;
  begin
    conv_s2s_4_6 = {{2{vector[3]}}, vector};
  end
  endfunction


  function signed [2:0] conv_s2s_2_3 ;
    input signed [1:0]  vector ;
  begin
    conv_s2s_2_3 = {vector[1], vector};
  end
  endfunction


  function signed [5:0] conv_u2s_5_6 ;
    input [4:0]  vector ;
  begin
    conv_u2s_5_6 = {1'b0, vector};
  end
  endfunction


  function signed [7:0] conv_u2s_7_8 ;
    input [6:0]  vector ;
  begin
    conv_u2s_7_8 = {1'b0, vector};
  end
  endfunction


  function signed [9:0] conv_u2s_8_10 ;
    input [7:0]  vector ;
  begin
    conv_u2s_8_10 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [7:0] conv_u2u_7_8 ;
    input [6:0]  vector ;
  begin
    conv_u2u_7_8 = {1'b0, vector};
  end
  endfunction


  function  [7:0] conv_u2u_6_8 ;
    input [5:0]  vector ;
  begin
    conv_u2u_6_8 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [9:0] conv_u2u_9_10 ;
    input [8:0]  vector ;
  begin
    conv_u2u_9_10 = {1'b0, vector};
  end
  endfunction


  function  [9:0] conv_u2u_8_10 ;
    input [7:0]  vector ;
  begin
    conv_u2u_8_10 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [6:0] conv_u2u_6_7 ;
    input [5:0]  vector ;
  begin
    conv_u2u_6_7 = {1'b0, vector};
  end
  endfunction


  function  [6:0] conv_u2u_5_7 ;
    input [4:0]  vector ;
  begin
    conv_u2u_5_7 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [2:0] conv_u2u_1_3 ;
    input [0:0]  vector ;
  begin
    conv_u2u_1_3 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [11:0] conv_u2s_10_12 ;
    input [9:0]  vector ;
  begin
    conv_u2s_10_12 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [12:0] conv_s2s_26_13 ;
    input signed [25:0]  vector ;
  begin
    conv_s2s_26_13 = vector[12:0];
  end
  endfunction


  function signed [12:0] conv_u2s_2_13 ;
    input [1:0]  vector ;
  begin
    conv_u2s_2_13 = {{11{1'b0}}, vector};
  end
  endfunction


  function  [1:0] conv_u2u_1_2 ;
    input [0:0]  vector ;
  begin
    conv_u2u_1_2 = {1'b0, vector};
  end
  endfunction


  function signed [12:0] conv_u2s_10_13 ;
    input [9:0]  vector ;
  begin
    conv_u2s_10_13 = {{3{1'b0}}, vector};
  end
  endfunction


  function  [5:0] conv_u2u_12_6 ;
    input [11:0]  vector ;
  begin
    conv_u2u_12_6 = vector[5:0];
  end
  endfunction


  function  [5:0] conv_u2u_2_6 ;
    input [1:0]  vector ;
  begin
    conv_u2u_2_6 = {{4{1'b0}}, vector};
  end
  endfunction


  function  [7:0] conv_u2u_16_8 ;
    input [15:0]  vector ;
  begin
    conv_u2u_16_8 = vector[7:0];
  end
  endfunction


  function  [7:0] conv_u2u_2_8 ;
    input [1:0]  vector ;
  begin
    conv_u2u_2_8 = {{6{1'b0}}, vector};
  end
  endfunction


  function  [6:0] conv_u2u_4_7 ;
    input [3:0]  vector ;
  begin
    conv_u2u_4_7 = {{3{1'b0}}, vector};
  end
  endfunction


  function  [4:0] conv_s2u_3_5 ;
    input signed [2:0]  vector ;
  begin
    conv_s2u_3_5 = {{2{vector[2]}}, vector};
  end
  endfunction


  function signed [12:0] conv_s2s_11_13 ;
    input signed [10:0]  vector ;
  begin
    conv_s2s_11_13 = {{2{vector[10]}}, vector};
  end
  endfunction


  function signed [10:0] conv_u2s_20_11 ;
    input [19:0]  vector ;
  begin
    conv_u2s_20_11 = vector[10:0];
  end
  endfunction


  function  [9:0] conv_u2u_2_10 ;
    input [1:0]  vector ;
  begin
    conv_u2u_2_10 = {{8{1'b0}}, vector};
  end
  endfunction


  function signed [10:0] conv_s2s_9_11 ;
    input signed [8:0]  vector ;
  begin
    conv_s2s_9_11 = {{2{vector[8]}}, vector};
  end
  endfunction


  function signed [8:0] conv_s2s_7_9 ;
    input signed [6:0]  vector ;
  begin
    conv_s2s_7_9 = {{2{vector[6]}}, vector};
  end
  endfunction


  function signed [6:0] conv_u2s_6_7 ;
    input [5:0]  vector ;
  begin
    conv_u2s_6_7 = {1'b0, vector};
  end
  endfunction


  function signed [6:0] conv_s2s_5_7 ;
    input signed [4:0]  vector ;
  begin
    conv_s2s_5_7 = {{2{vector[4]}}, vector};
  end
  endfunction


  function signed [8:0] conv_u2s_7_9 ;
    input [6:0]  vector ;
  begin
    conv_u2s_7_9 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [12:0] conv_s2s_12_13 ;
    input signed [11:0]  vector ;
  begin
    conv_s2s_12_13 = {vector[11], vector};
  end
  endfunction


  function signed [11:0] conv_s2s_24_12 ;
    input signed [23:0]  vector ;
  begin
    conv_s2s_24_12 = vector[11:0];
  end
  endfunction


  function signed [11:0] conv_s2s_2_12 ;
    input signed [1:0]  vector ;
  begin
    conv_s2s_2_12 = {{10{vector[1]}}, vector};
  end
  endfunction


  function signed [10:0] conv_s2s_22_11 ;
    input signed [21:0]  vector ;
  begin
    conv_s2s_22_11 = vector[10:0];
  end
  endfunction


  function signed [10:0] conv_s2s_2_11 ;
    input signed [1:0]  vector ;
  begin
    conv_s2s_2_11 = {{9{vector[1]}}, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    sobel
//  Generated from file(s):
//    7) $PROJECT_HOME/sobel.cpp
// ------------------------------------------------------------------


module sobel (
  vin_rsc_z, vout_rsc_z, clk, en, arst_n
);
  input [89:0] vin_rsc_z;
  output [29:0] vout_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [89:0] vin_rsc_mgc_in_wire_d;
  wire [29:0] vout_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(90)) vin_rsc_mgc_in_wire (
      .d(vin_rsc_mgc_in_wire_d),
      .z(vin_rsc_z)
    );
  mgc_out_stdreg #(.rscid(2),
  .width(30)) vout_rsc_mgc_out_stdreg (
      .d(vout_rsc_mgc_out_stdreg_d),
      .z(vout_rsc_z)
    );
  sobel_core sobel_core_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .vin_rsc_mgc_in_wire_d(vin_rsc_mgc_in_wire_d),
      .vout_rsc_mgc_out_stdreg_d(vout_rsc_mgc_out_stdreg_d)
    );
endmodule



