// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   mg3115@EEWS104A-006
//  Generated date: Thu May 12 09:33:00 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    sound_clk_core
// ------------------------------------------------------------------


module sound_clk_core (
  clk, en, arst_n, vga_xy_rsc_mgc_in_wire_d, play_clk_rsc_mgc_out_stdreg_d
);
  input clk;
  input en;
  input arst_n;
  input [19:0] vga_xy_rsc_mgc_in_wire_d;
  output play_clk_rsc_mgc_out_stdreg_d;
  reg play_clk_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(posedge clk or negedge arst_n) begin
    if ( ~ arst_n ) begin
      play_clk_rsc_mgc_out_stdreg_d <= 1'b0;
    end
    else begin
      if ( en ) begin
        play_clk_rsc_mgc_out_stdreg_d <= ~((readslicef_11_1_10((conv_u2s_10_11(vga_xy_rsc_mgc_in_wire_d[19:10])
            + 11'b11000001001))) | (readslicef_10_1_9((conv_u2u_9_10(vga_xy_rsc_mgc_in_wire_d[9:1])
            + 10'b1010001001))));
      end
    end
  end

  function [0:0] readslicef_11_1_10;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 10;
    readslicef_11_1_10 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_10_1_9;
    input [9:0] vector;
    reg [9:0] tmp;
  begin
    tmp = vector >> 9;
    readslicef_10_1_9 = tmp[0:0];
  end
  endfunction


  function signed [10:0] conv_u2s_10_11 ;
    input [9:0]  vector ;
  begin
    conv_u2s_10_11 = {1'b0, vector};
  end
  endfunction


  function  [9:0] conv_u2u_9_10 ;
    input [8:0]  vector ;
  begin
    conv_u2u_9_10 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    sound_clk
//  Generated from file(s):
//    2) //icnas3.cc.ic.ac.uk/mg3115/sound_clk/sound_clk.cpp
// ------------------------------------------------------------------


module sound_clk (
  vga_xy_rsc_z, play_clk_rsc_z, clk, en, arst_n
);
  input [19:0] vga_xy_rsc_z;
  output play_clk_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [19:0] vga_xy_rsc_mgc_in_wire_d;
  wire play_clk_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(20)) vga_xy_rsc_mgc_in_wire (
      .d(vga_xy_rsc_mgc_in_wire_d),
      .z(vga_xy_rsc_z)
    );
  mgc_out_stdreg #(.rscid(2),
  .width(1)) play_clk_rsc_mgc_out_stdreg (
      .d(play_clk_rsc_mgc_out_stdreg_d),
      .z(play_clk_rsc_z)
    );
  sound_clk_core sound_clk_core_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .vga_xy_rsc_mgc_in_wire_d(vga_xy_rsc_mgc_in_wire_d),
      .play_clk_rsc_mgc_out_stdreg_d(play_clk_rsc_mgc_out_stdreg_d)
    );
endmodule



