// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   dm2515@EEWS104A-003
//  Generated date: Tue May 03 13:47:55 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    pixel_detect_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module pixel_detect_core_fsm (
  clk, rst, fsm_output
);
  input clk;
  input rst;
  output [1:0] fsm_output;
  reg [1:0] fsm_output;


  // FSM State Type Declaration for pixel_detect_core_fsm_1
  parameter
    st_main = 1'd0,
    st_main_1 = 1'd1,
    state_x = 1'b0;

  reg [0:0] state_var;
  reg [0:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : pixel_detect_core_fsm_1
    case (state_var)
      st_main : begin
        fsm_output = 2'b1;
        state_var_NS = st_main_1;
      end
      st_main_1 : begin
        fsm_output = 2'b10;
        state_var_NS = st_main;
      end
      default : begin
        fsm_output = 2'b00;
        state_var_NS = st_main;
      end
    endcase
  end

  always @(posedge clk) begin
    if ( rst ) begin
      state_var <= st_main;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    pixel_detect_core
// ------------------------------------------------------------------


module pixel_detect_core (
  clk, rst, vga_xy_rsc_mgc_in_wire_d, video_in_rsc_mgc_in_wire_d, video_out_rsc_mgc_out_stdreg_d,
      redY_rsc_mgc_out_stdreg_d, redX_rsc_mgc_out_stdreg_d
);
  input clk;
  input rst;
  input [19:0] vga_xy_rsc_mgc_in_wire_d;
  input [29:0] video_in_rsc_mgc_in_wire_d;
  output [29:0] video_out_rsc_mgc_out_stdreg_d;
  reg [29:0] video_out_rsc_mgc_out_stdreg_d;
  output [9:0] redY_rsc_mgc_out_stdreg_d;
  reg [9:0] redY_rsc_mgc_out_stdreg_d;
  output [9:0] redX_rsc_mgc_out_stdreg_d;
  reg [9:0] redX_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations
  wire [1:0] fsm_output;
  wire or_3_cse;


  // Interconnect Declarations for Component Instantiations 
  pixel_detect_core_fsm pixel_detect_core_fsm_inst (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output)
    );
  assign or_3_cse = (~((fsm_output[0]) & (readslicef_11_1_10((({1'b1 , (~ (video_in_rsc_mgc_in_wire_d[29:20]))})
      + 11'b11100111))) & (readslicef_10_1_9((conv_u2u_9_10(video_in_rsc_mgc_in_wire_d[19:11])
      + 10'b1111110001))))) | (~ (readslicef_10_1_9((conv_u2u_9_10(video_in_rsc_mgc_in_wire_d[9:1])
      + 10'b1111110001)))) | (readslicef_7_1_6((({1'b1 , (~ (vga_xy_rsc_mgc_in_wire_d[9:4]))})
      + 7'b11101)));
  always @(posedge clk) begin
    if ( rst ) begin
      redX_rsc_mgc_out_stdreg_d <= 10'b0;
      redY_rsc_mgc_out_stdreg_d <= 10'b0;
      video_out_rsc_mgc_out_stdreg_d <= 30'b0;
    end
    else begin
      redX_rsc_mgc_out_stdreg_d <= MUX_v_10_2_2({({1'b0 , (vga_xy_rsc_mgc_in_wire_d[8:0])})
          , redX_rsc_mgc_out_stdreg_d}, or_3_cse);
      redY_rsc_mgc_out_stdreg_d <= MUX_v_10_2_2({(vga_xy_rsc_mgc_in_wire_d[19:10])
          , redY_rsc_mgc_out_stdreg_d}, or_3_cse);
      video_out_rsc_mgc_out_stdreg_d <= MUX_v_30_2_2({video_out_rsc_mgc_out_stdreg_d
          , video_in_rsc_mgc_in_wire_d}, fsm_output[0]);
    end
  end

  function [0:0] readslicef_11_1_10;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 10;
    readslicef_11_1_10 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_10_1_9;
    input [9:0] vector;
    reg [9:0] tmp;
  begin
    tmp = vector >> 9;
    readslicef_10_1_9 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_7_1_6;
    input [6:0] vector;
    reg [6:0] tmp;
  begin
    tmp = vector >> 6;
    readslicef_7_1_6 = tmp[0:0];
  end
  endfunction


  function [9:0] MUX_v_10_2_2;
    input [19:0] inputs;
    input [0:0] sel;
    reg [9:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[19:10];
      end
      1'b1 : begin
        result = inputs[9:0];
      end
      default : begin
        result = inputs[19:10];
      end
    endcase
    MUX_v_10_2_2 = result;
  end
  endfunction


  function [29:0] MUX_v_30_2_2;
    input [59:0] inputs;
    input [0:0] sel;
    reg [29:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[59:30];
      end
      1'b1 : begin
        result = inputs[29:0];
      end
      default : begin
        result = inputs[59:30];
      end
    endcase
    MUX_v_30_2_2 = result;
  end
  endfunction


  function  [9:0] conv_u2u_9_10 ;
    input [8:0]  vector ;
  begin
    conv_u2u_9_10 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    pixel_detect
//  Generated from file(s):
//    9) $PROJECT_HOME/vga_mouse.cpp
// ------------------------------------------------------------------


module pixel_detect (
  vga_xy_rsc_z, video_in_rsc_z, video_out_rsc_z, redY_rsc_z, redX_rsc_z, clk, rst
);
  input [19:0] vga_xy_rsc_z;
  input [29:0] video_in_rsc_z;
  output [29:0] video_out_rsc_z;
  output [9:0] redY_rsc_z;
  output [9:0] redX_rsc_z;
  input clk;
  input rst;


  // Interconnect Declarations
  wire [19:0] vga_xy_rsc_mgc_in_wire_d;
  wire [29:0] video_in_rsc_mgc_in_wire_d;
  wire [29:0] video_out_rsc_mgc_out_stdreg_d;
  wire [9:0] redY_rsc_mgc_out_stdreg_d;
  wire [9:0] redX_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(20)) vga_xy_rsc_mgc_in_wire (
      .d(vga_xy_rsc_mgc_in_wire_d),
      .z(vga_xy_rsc_z)
    );
  mgc_in_wire #(.rscid(2),
  .width(30)) video_in_rsc_mgc_in_wire (
      .d(video_in_rsc_mgc_in_wire_d),
      .z(video_in_rsc_z)
    );
  mgc_out_stdreg #(.rscid(3),
  .width(30)) video_out_rsc_mgc_out_stdreg (
      .d(video_out_rsc_mgc_out_stdreg_d),
      .z(video_out_rsc_z)
    );
  mgc_out_stdreg #(.rscid(4),
  .width(10)) redY_rsc_mgc_out_stdreg (
      .d(redY_rsc_mgc_out_stdreg_d),
      .z(redY_rsc_z)
    );
  mgc_out_stdreg #(.rscid(5),
  .width(10)) redX_rsc_mgc_out_stdreg (
      .d(redX_rsc_mgc_out_stdreg_d),
      .z(redX_rsc_z)
    );
  pixel_detect_core pixel_detect_core_inst (
      .clk(clk),
      .rst(rst),
      .vga_xy_rsc_mgc_in_wire_d(vga_xy_rsc_mgc_in_wire_d),
      .video_in_rsc_mgc_in_wire_d(video_in_rsc_mgc_in_wire_d),
      .video_out_rsc_mgc_out_stdreg_d(video_out_rsc_mgc_out_stdreg_d),
      .redY_rsc_mgc_out_stdreg_d(redY_rsc_mgc_out_stdreg_d),
      .redX_rsc_mgc_out_stdreg_d(redX_rsc_mgc_out_stdreg_d)
    );
endmodule



